# Generated by Django 3.1.3 on 2020-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('categroy', models.CharField(choices=[(0, '技术类'), (1, '非技术类')], default=0, max_length=10, verbose_name='文章分类')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
                'db_table': 'Topics',
            },
        ),
    ]
